---

- name: Install apache2 packages
  become: true
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: "Configure apache2"
  template: src={{ item.src }} dest={{ item.dest }}
            owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  become: true
  notify: restart-apache2
  with_items:
  - { src: 'apache2/apache2.conf', dest: '/etc/apache2/apache2.conf', owner: 'root', group: 'root', mode: '0600' }